from .base_repo import BaseRepository
from models import Category
from sqlalchemy.future import select



class CategoryRepository(BaseRepository):
    """
    Repository for Category model. Handles all database operations related to categories.
    All methods are asynchronous and expect an async SQLAlchemy session.
    """

    def __init__(self, session):
        """
        Initialize repository with a database session.
        :param session: Async SQLAlchemy session
        """
        self.session = session

    async def get_by_ids(self, ids: list[int]) -> list[Category]:
        """
        Retrieve multiple categories by their IDs.
        :param ids: List of Category IDs
        :return: List of Category instances
        """
        result = await self.session.execute(
            select(Category).where(Category.id.in_(ids))
        )
        return result.scalars().all()

    async def get_all(self) -> list[Category]:
        """
        Retrieve all categories from the database.
        :return: List of Category instances
        """
        result = await self.session.execute(select(Category))
        return result.scalars().all()
    
    async def get_by_id(self, id: int) -> Category:
        """
        Retrieve a category by its ID.
        :param id: Category ID
        :return: Category instance or None if not found
        """
        result = await self.session.get(Category, id)
        return result
    
    async def get_by_name(self, name: str) -> Category:
        """
        Retrieve a category by its name.
        :param name: Category name
        :return: Category instance or None if not found
        """
        result = await self.session.execute(
            select(Category).where(Category.name == name)
        )
        return result.scalars().first()
    
    async def create(self, obj: Category) -> Category:
        """
        Add a new category to the database.
        Commits and refreshes the object to get updated fields (e.g., autogenerated ID).
        :param obj: Category instance
        :return: Created Category instance
        """
        self.session.add(obj)
        await self.session.commit()
        await self.session.refresh(obj)
        return obj
    
    async def update(self, id: int, update_data: dict) -> Category:
        """
        Update an existing category with the provided data.
        :param id: Category ID
        :param update_data: Dictionary of fields to update
        :return: Updated Category instance or None if not found
        Note: update_data should be a dict, not a Category model instance.
        """
        existing_category = await self.get_by_id(id)
        if not existing_category:
            return None
        for key, value in update_data.items():
            setattr(existing_category, key, value)
        self.session.add(existing_category)
        await self.session.commit()
        await self.session.refresh(existing_category)
        return existing_category
    
    async def delete(self, id: int) -> bool:
        """
        Delete a category by its ID.
        :param id: Category ID
        :return: True if deleted, False if not found
        """
        existing_category = await self.get_by_id(id)
        if not existing_category:
            return False
        await self.session.delete(existing_category)
        await self.session.commit()
        return True