from .base_repo import BaseRepository
from models import OrderItem
from sqlalchemy.future import select



class OrderItemRepository(BaseRepository):
    """
    Repository for OrderItem model. Handles all database operations related to order items.
    All methods are asynchronous and expect an async SQLAlchemy session.
    """

    def __init__(self, session):
        """
        Initialize repository with a database session.
        :param session: Async SQLAlchemy session
        """
        self.session = session

    async def create(self, obj: OrderItem) -> OrderItem:
        """
        Add a new order item to the database.
        Commits and refreshes the object to get updated fields (e.g., autogenerated ID).
        :param obj: OrderItem instance
        :return: Created OrderItem instance
        """
        self.session.add(obj)
        await self.session.commit()
        await self.session.refresh(obj)
        return obj
    
    async def get_by_id(self, id: int) -> OrderItem:
        """
        Retrieve an order item by its ID.
        :param id: OrderItem ID
        :return: OrderItem instance or None if not found
        """
        result = await self.session.get(OrderItem, id)
        return result
    
    async def get_all(self) -> list[OrderItem]:
        """
        Retrieve all order items from the database.
        :return: List of OrderItem instances
        """
        result = await self.session.execute(select(OrderItem))
        return result.scalars().all()
    
    
    async def stock_reduction(self, product_id: int, quantity: int) -> OrderItem:
        """
        Reduce the stock (quantity) of an order item for a given product.
        :param product_id: Product ID
        :param quantity: Quantity to reduce
        :return: Updated OrderItem instance or None if not found or insufficient stock
        """
        result = await self.session.execute(
            select(OrderItem).where(
                OrderItem.product_id == product_id,
                OrderItem.quantity >= quantity
            )
        )
        order_item = result.scalars().first()
        if order_item:
            order_item.quantity -= quantity
            self.session.add(order_item)
            await self.session.commit()
            await self.session.refresh(order_item)
            return order_item
        else:
            return None
        
    async def get_by_order_id(self, order_id: int) -> list[OrderItem]:
        """
        Retrieve all order items for a specific order.
        :param order_id: Order ID
        :return: List of OrderItem instances
        """
        result = await self.session.execute(
            select(OrderItem).where(OrderItem.order_id == order_id)
        )
        return result.scalars().all()
    async def update(self, id: int, update_data: dict) -> OrderItem:
        """
        Update an existing order item with the provided data.
        :param id: OrderItem ID
        :param update_data: Dictionary of fields to update
        :return: Updated OrderItem instance or None if not found
        Note: update_data should be a dict, not an OrderItem model instance.
        """
        existing_order_item = await self.get_by_id(id)
        if not existing_order_item:
            return None
        for key, value in update_data.items():
            setattr(existing_order_item, key, value)
        self.session.add(existing_order_item)
        await self.session.commit()
        await self.session.refresh(existing_order_item)
        return existing_order_item
    
    async def delete(self, id: int) -> bool:
        """
        Delete an order item by its ID.
        :param id: OrderItem ID
        :return: True if deleted, False if not found
        """
        existing_order_item = await self.get_by_id(id)
        if not existing_order_item:
            return False
        await self.session.delete(existing_order_item)
        await self.session.commit()
        return True