from .base_repo import BaseRepository
from models import Review
from sqlalchemy.future import select
from typing import Optional


class ReviewRepository(BaseRepository):

    """
    Repository for Review model. Handles all database operations related to reviews.
    All methods are asynchronous and expect an async SQLAlchemy session.
    """

    def __init__(self, session):
        """
        Initialize repository with a database session.
        :param session: Async SQLAlchemy session
        """
        self.session = session

    async def create(self, obj: Review) -> Review:
        """
        Add a new review to the database.
        Commits and refreshes the object to get updated fields (e.g., autogenerated ID).
        :param obj: Review instance
        :return: Created Review instance
        """
        self.session.add(obj)
        await self.session.commit()
        await self.session.refresh(obj)
        return obj
    
    async def get_by_id(self, id: int) -> Optional[Review]:
        """
        Retrieve a review by its ID.
        :param id: Review ID
        :return: Review instance or None if not found
        """
        result = await self.session.get(Review, id)
        return result
    
    async def get_all(self) -> list[Review]:
        """
        Retrieve all reviews from the database.
        :return: List of Review instances
        """
        result = await self.session.execute(select(Review))
        return result.scalars().all()
    
    async def get_by_product_id(self, product_id: int) -> list[Review]:
        """
        Retrieve all reviews for a specific product.
        :param product_id: Product ID
        :return: List of Review instances
        """
        result = await self.session.execute(select(Review).where(Review.product_id == product_id))
        return result.scalars().all()
    
    async def get_by_user_id(self, user_id: int) -> list[Review]:
        """
        Retrieve all reviews for a specific user.
        :param user_id: User ID
        :return: List of Review instances
        """
        result = await self.session.execute(select(Review).where(Review.user_id == user_id))
        return result.scalars().all()
    
    async def update(self, id: int, update_data: dict) -> Review:
        """
        Update an existing review with the provided data.
        :param id: Review ID
        :param update_data: Dictionary of fields to update
        :return: Updated Review instance or None if not found
        Note: update_data should be a dict, not a Review model instance.
        """
        existing_review = await self.get_by_id(id)
        if not existing_review:
            return None
        for key, value in update_data.items():
            setattr(existing_review, key, value)
        self.session.add(existing_review)
        await self.session.commit()
        await self.session.refresh(existing_review)
        return existing_review
    
    async def delete(self, id: int) -> bool:
        """
        Delete a review by its ID.
        :param id: Review ID
        :return: True if deleted, False if not found
        """
        existing_review = await self.get_by_id(id)
        if not existing_review:
            return False
        await self.session.delete(existing_review)
        await self.session.commit()
        return True